# Form implementation generated from reading ui file 'qtUI/tabs.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class MainWindow(QtWidgets.QMainWindow):
    rootItemSpeedSetted = QtCore.pyqtSignal(float)

    def __init__(self, mainWindow: QtWidgets.QMainWindow, itemsListTableView: QtWidgets.QTableView, graphicsView: QtWidgets.QGraphicsView, itemTableView: QtWidgets.QTableView, machineTableView: QtWidgets.QTableView):
        super().__init__(mainWindow)
        self.itemsListTableView = itemsListTableView 
        self.graphicsView = graphicsView 
        self.itemTableView = itemTableView 
        self.machineTableView = machineTableView
        self.setupUi()

    def on__editing_finnished(self):
        self.rootItemSpeedSetted.emit(self.rootItemSpeedSpinBox.value())

    def getRootItemSpeed(self):
        return self.rootItemSpeedSpinBox.value()

    def setupUi(self):
        self.setObjectName("MainWindow")
        self.resize(800, 600)
        self.setMinimumSize(QtCore.QSize(800, 600))
        self.setDocumentMode(False)
        self.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(parent=self)
        self.centralwidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget.setAutoFillBackground(True)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.searchTab = QtWidgets.QWidget()
        self.searchTab.setObjectName("searchTabRows")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.searchTab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.searchTabColumns = QtWidgets.QHBoxLayout()
        self.searchTabColumns.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMinimumSize)
        self.searchTabColumns.setObjectName("searchTabColumns")
        self.searchLine = QtWidgets.QLineEdit(parent=self.searchTab)
        self.searchLine.setObjectName("searchLine")
        self.searchTabColumns.addWidget(self.searchLine)
        self.searchButton = QtWidgets.QPushButton(parent=self.searchTab)
        self.searchButton.setObjectName("searchButton")
        self.searchTabColumns.addWidget(self.searchButton)
        self.verticalLayout_2.addLayout(self.searchTabColumns)
        self.itemsListTableView.setParent(self.searchTab)
        self.itemsListTableView.setObjectName("itemMetaListModel")
        self.verticalLayout_2.addWidget(self.itemsListTableView)
        self.tabWidget.addTab(self.searchTab, "")
        self.craftTab = QtWidgets.QWidget()
        self.craftTab.setObjectName("craftTab")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.craftTab)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.craftTabHSplitter = QtWidgets.QSplitter(parent=self.craftTab)
        self.craftTabHSplitter.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.craftTabHSplitter.setObjectName("craftTabHSplitter")
        self.craftTabHSplitter.setStretchFactor(0, 2)
        self.craftTabHSplitter.setStretchFactor(1, 1)
        self.graphicsView.setParent(self.craftTabHSplitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        self.graphicsView.setSizePolicy(sizePolicy)
        self.graphicsView.setObjectName("graphicsView")
        self.craftTabVSplitter = QtWidgets.QSplitter(parent=self.craftTabHSplitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.craftTabVSplitter.sizePolicy().hasHeightForWidth())
        self.craftTabVSplitter.setSizePolicy(sizePolicy)
        self.craftTabVSplitter.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.craftTabVSplitter.setObjectName("craftTabVSplitter")

        self.rootItemSpeedGroup = QtWidgets.QGroupBox(parent=self.craftTabVSplitter)
        self.rootItemSpeedGroup.setObjectName("rootItemSpeedGroup")
        self.rootItemSpeedGroupLayout = QtWidgets.QVBoxLayout(self.rootItemSpeedGroup)

        self.rootItemSpeedSpinBox = QtWidgets.QDoubleSpinBox()
        self.rootItemSpeedSpinBox.setObjectName("rootItemSpeedSpinBox")
        self.rootItemSpeedSpinBox.setDecimals(2)
        self.rootItemSpeedSpinBox.setValue(1)
        self.rootItemSpeedSpinBox.editingFinished.connect(self.on__editing_finnished)
        self.rootItemSpeedGroupLayout.addWidget(self.rootItemSpeedSpinBox)


        self.itemTableViewGroup = QtWidgets.QGroupBox(parent=self.craftTabVSplitter)
        self.itemTableViewGroup.setObjectName("itemTableViewGroup")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.itemTableViewGroup)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.itemTableView.setParent(self.itemTableViewGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.itemTableView.sizePolicy().hasHeightForWidth())
        self.itemTableView.setSizePolicy(sizePolicy)
        self.itemTableView.setObjectName("itemTableView")
        self.verticalLayout_7.addWidget(self.itemTableView)

        self.machineTableViewGroup = QtWidgets.QGroupBox(parent=self.craftTabVSplitter)
        self.machineTableViewGroup.setObjectName("machineTableViewGroup")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.machineTableViewGroup)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.machineTableView.setParent(self.machineTableViewGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.machineTableView.sizePolicy().hasHeightForWidth())
        self.machineTableView.setSizePolicy(sizePolicy)
        self.machineTableView.setObjectName("machineTableView")
        self.verticalLayout_8.addWidget(self.machineTableView)
        self.verticalLayout_9.addWidget(self.craftTabHSplitter)
        self.tabWidget.addTab(self.craftTab, "")
        self.verticalLayout_6.addWidget(self.tabWidget)
        self.setCentralWidget(self.centralwidget)

        self.retranslateUi(self)
        self.tabWidget.setCurrentIndex(0)

    def retranslateUi(self, MainWindow: QtWidgets.QMainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "FCV2"))
        self.searchButton.setText(_translate("MainWindow", "Search"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.searchTab), _translate("MainWindow", "searchTab"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.craftTab), _translate("MainWindow", "craftTab"))
        self.rootItemSpeedGroup.setTitle(_translate("MainWindow", "Root Item Speed"))
        self.itemTableViewGroup.setTitle(_translate("MainWindow", "Item"))
        self.machineTableViewGroup.setTitle(_translate("MainWindow", "Machine"))